version: '3'
services:
  flask-server:
    build: .
    ports:
      - '8000:8000'
    environment:
      - CELERY_BROKER_URL=redis://host.docker.internal:6379/0
      - CELERY_RESULT_BACKEND=redis://host.docker.internal:6379/0

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://host.docker.internal:6379/0
    command: celery flower --port=5555
    ports:
      - '5555:5555'
