FROM pytorch/pytorch:latest

WORKDIR /app

# Use the environment variable to write the token to the file
RUN mkdir -p ~/.huggingface
RUN echo -n $HUGGINGFACE_TOKEN > ~/.huggingface/token

# Update system and install necessary system packages for git and wget
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y git wget python3-dev build-essential libgl1-mesa-glx
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --no-install-recommends libglib2.0-0 && rm -rf /var/lib/apt/lists/*

# Clone the repository
RUN git clone -b run-sdxl-dreambooth https://github.com/samarsheikh001/job_queue_template .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r worker/requirements.txt

RUN pip install -U autotrain-advanced

RUN autotrain setup --update-torch

# Set environment variable
ENV PYTHONUNBUFFERED 1

# Run celery worker when the container launches
CMD celery -A app.celery worker --loglevel INFO --pool solo -c 1 -f celery.logs -Q ${QUEUE}