version: '3'
services:
  flask-server:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - ./flask-app:/home/myuser

  flower:
    image: mher/flower
    command: flower --broker=redis://redis:6379/0 --port=5555
    ports:
      - '5555:5555'
