version: '3'
services:
  flask-server:
    build:
      context: .
      dockerfile: Dockerfile_flask
    ports:
      - '8000:8000'
    environment:
      - CELERY_ENV=server
    env_file:
      - .env

  flower:
    image: mher/flower
    environment:
      - FLOWER_UNAUTHENTICATED_API=True
    env_file:
      - .env
    command: celery flower --port=5555
    ports:
      - '5555:5555'
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
