version: '3'
services:
  flask-server:
    build: .
    ports:
      - '8000:8000'
  # flower:
  #   image: mher/flower
  #   environment:
  #     - CELERY_BROKER_URL=redis://<your-redis-host>:<your-redis-port>/0
  #   command: flower --port=5555
  #   ports:
  #     - '5555:5555'
